<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Words" Version="26.1.0" />
    <PackageReference Include="IPO.Common.Infrastructure" Version="2.0.424213" />
	  <PackageReference Include="SkiaSharp" Version="3.119.2" />
	  <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2" />
    <PackageReference Include="Spire.PDFfor.NETStandard" Version="11.12.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IPO.FileSanitise.Interfaces\IPO.FileSanitise.Interfaces.csproj" />
    <ProjectReference Include="..\IPO.FileSanitise.Models\IPO.FileSanitise.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>IPO.FileSanitise.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
